// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8OTFSHGWql5DAT5cGOKwgX2RbU_SHt4w',
    appId: '1:961147410824:web:0ce4a3cbbcb8f4d21e423d',
    messagingSenderId: '961147410824',
    projectId: 'sochic-threads-flutter-clone',
    authDomain: 'sochic-threads-flutter-clone.firebaseapp.com',
    storageBucket: 'sochic-threads-flutter-clone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Edoab_AsJP2MR1tTXrBHUa0PUnP4ieQ',
    appId: '1:961147410824:android:6baf047b3a99ce9e1e423d',
    messagingSenderId: '961147410824',
    projectId: 'sochic-threads-flutter-clone',
    storageBucket: 'sochic-threads-flutter-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbz3l0Nh2npd9rf6Go0RZ4hwqMbrYc_fY',
    appId: '1:961147410824:ios:b45230a5f924fba81e423d',
    messagingSenderId: '961147410824',
    projectId: 'sochic-threads-flutter-clone',
    storageBucket: 'sochic-threads-flutter-clone.firebasestorage.app',
    iosBundleId: 'com.sooooochic.threadsClone',
  );

}