// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6MrlRJn3nGmi3pBvEjyEvaKOtrhA8vyc',
    appId: '1:1079515373269:web:f99bd54b40cd8121914c5c',
    messagingSenderId: '1079515373269',
    projectId: 'sochic-moodtracker-flutter',
    authDomain: 'sochic-moodtracker-flutter.firebaseapp.com',
    storageBucket: 'sochic-moodtracker-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmnAt6o5Q59ZNlN24t5V5RHLKLloE6qsA',
    appId: '1:1079515373269:android:4b3045f4ef197a4d914c5c',
    messagingSenderId: '1079515373269',
    projectId: 'sochic-moodtracker-flutter',
    storageBucket: 'sochic-moodtracker-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHed83e3fuNzdq29EmA5waDmBn9IfajWE',
    appId: '1:1079515373269:ios:473c1192fd8f6b0c914c5c',
    messagingSenderId: '1079515373269',
    projectId: 'sochic-moodtracker-flutter',
    storageBucket: 'sochic-moodtracker-flutter.firebasestorage.app',
    iosBundleId: 'com.example.moodTracker',
  );

}