// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy407Jnlorr4525flpVAhihNGvXayNwjw',
    appId: '1:261872585224:web:efdb0a13bd30a1c7431fbd',
    messagingSenderId: '261872585224',
    projectId: 'sochic-tiktok-flutter-clone',
    authDomain: 'sochic-tiktok-flutter-clone.firebaseapp.com',
    storageBucket: 'sochic-tiktok-flutter-clone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQOuVWFCg8wl0T8qqW-SbWbQscXGEC4iw',
    appId: '1:261872585224:android:754a1290eb3c577d431fbd',
    messagingSenderId: '261872585224',
    projectId: 'sochic-tiktok-flutter-clone',
    storageBucket: 'sochic-tiktok-flutter-clone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdKbe9huEhYNzK61pPFHCpiMiqOnQM1Bo',
    appId: '1:261872585224:ios:b2ae16d9434a3ab6431fbd',
    messagingSenderId: '261872585224',
    projectId: 'sochic-tiktok-flutter-clone',
    storageBucket: 'sochic-tiktok-flutter-clone.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );

}