// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5N-8ofPrSaoZEaITfhwbHabueGyhYuWs',
    appId: '1:398253758562:web:87694e49b1fc2da927d93b',
    messagingSenderId: '398253758562',
    projectId: 'sochic-assignment26-flutter',
    authDomain: 'sochic-assignment26-flutter.firebaseapp.com',
    storageBucket: 'sochic-assignment26-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwjqUyZbsEOxR8Sh8I92fCUJcdcsLW_xo',
    appId: '1:398253758562:android:b8e8696aa0a6acd427d93b',
    messagingSenderId: '398253758562',
    projectId: 'sochic-assignment26-flutter',
    storageBucket: 'sochic-assignment26-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKJoa6OHPNQ0eP8IoIQ9rQuMSnDPqIWRQ',
    appId: '1:398253758562:ios:a6b1bf1d0ef54bf527d93b',
    messagingSenderId: '398253758562',
    projectId: 'sochic-assignment26-flutter',
    storageBucket: 'sochic-assignment26-flutter.firebasestorage.app',
    iosBundleId: 'com.example.assignment26',
  );

}